Chapter 7 Outline
merely-useful/r-rse pull request #84
Opened 2021-04-20 23:07 UTC by ian-flores

This PR includes the outline for chapter 7: Build management and workflow

2021-04-22 16:32 UTC, cwickham requested changes
Looks really great Ian!  

A few minor comments in the review, once addressed, this is ready to merge!

2021-04-22 16:32 UTC, cwickham commented on chapters/07-build-management.Rmd
> +* Deploy a GitHub Action that runs a continuous integration workflow
I like learning objectives to use verbs that almost describe the way they could be assessed, i.e. be measurable - "aquaint" and "understand" are a little too non-specific.  How about:
```suggestion
* Describe the functionality devtools provides to manage an R package infrastructure
* Explain the CRAN checks' process and the different components
* Implement the workflow to validate an R package locally
* Deploy a GitHub Action that runs a continuous integration workflow
```

2021-05-03 00:43 UTC, ian-flores commented
@cwickham I've updated the chapter with your recs. Thanks for your review!

2021-05-03 23:47 UTC, cwickham commented
@ian-flores Looks great!

2021-05-03 23:48 UTC, merged